### ISSUE TITLE
[feat] Create a radio button group that displays all table names

### ISSUE THREAD

**Issue by malabudi** [malabudi/devfest-admin-fe#4]
The component will show a group of radio buttons with all tables to be selected, only one can be selected at a time.

![image](https://github.com/user-attachments/assets/5229d355-8652-46da-8f8c-b46e371a7a6a)

Figma: https://www.figma.com/design/XqP2VJhBDqmEfPYNvSFMUq/DevFest-Admin?node-id=0-1&t=To5MQXiTiyJ09SG8-1

**Comment by malabudi** [comment]
The page for this will be added in the figma by this coming Monday, it doesn't currently exist but you can for now just focus on adding the buttons as best as you can without regards to the styling

**Comment by JuanLinaresOrihuela** [comment]
Understood! I will try my best to complete it by Saturday afternoon!

**Comment by malabudi** [comment]
> I've the repo and the structure for the app hasn't been created yet. Are we using TS or JS?

![image](https://github.com/user-attachments/assets/af15f715-87ee-497b-9ca2-4296c2708393)
Your gonna have to clone the repo locally and create the branch directly within your issue
