### ISSUE TITLE
[feat] Add modal when deleting a row to confirm deletion

### ISSUE THREAD

**Issue by malabudi** [malabudi/devfest-admin-fe#6]
Similar to the edit modal, just have the modal ask the user if they are sure they want to delete the record, with a Yes or No buttons.

Figma: https://www.figma.com/design/XqP2VJhBDqmEfPYNvSFMUq/DevFest-Admin?node-id=0-1&t=To5MQXiTiyJ09SG8-1

**Comment by Tej619** [comment]
completed and merged
